version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 16379:6379
    volumes:
      - ./data/redis:/data
