version: '3.4'

services:
  mqtt-store:
    image: local/${DOCKER_TEMPLATE}
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
